Css canvas medical
Logisticx/rc0522-code-solutions pull request #26
Opened 2022-05-17 02:36 UTC by Logisticx

![image](https://user-images.githubusercontent.com/103016667/168716765-a4c580f9-30d4-43a8-9bf3-51abcf25755e.png)
![image](https://user-images.githubusercontent.com/103016667/168716805-ff1b6c6a-dfd7-4d19-b307-55bf666fe7e4.png)

2022-05-17 07:47 UTC, Logisticx commented
![image](https://user-images.githubusercontent.com/103016667/168757928-88e12fc1-d0ba-4567-ba41-024024063cbe.png)
![image](https://user-images.githubusercontent.com/103016667/168757958-31c8e4c0-ac60-4fe0-82a8-3346a9eed954.png)

2022-05-17 17:46 UTC, Zhiwutian requested changes
make sure to add `margin: 0 auto` so that the container is centered on the page.

2022-05-17 23:37 UTC, Logisticx commented
![image](https://user-images.githubusercontent.com/103016667/168929109-ab24436b-f8a5-477f-a1b7-7dcb04916056.png)

![image](https://user-images.githubusercontent.com/103016667/168929060-a0e7f999-bbff-4eab-aff5-0b12c9822af7.png)

2022-05-18 00:04 UTC, Zhiwutian approved these changes
👍🏼

2022-05-18 01:14 UTC, merged