completed javascript-if
Logisticx/rc0522-code-solutions pull request #34
Opened 2022-05-18 22:00 UTC by le-andre

![image](https://user-images.githubusercontent.com/103016667/169162962-d3ebdfd0-4034-4a77-9bce-c88dadf5287a.png)

2022-05-18 22:07 UTC, TimelikeClosure requested changes

2022-05-18 22:07 UTC, TimelikeClosure commented on javascript-if/main.js
> +}
People under 16 should not be old enough to drink and drive.

2022-05-18 22:07 UTC, TimelikeClosure commented on javascript-if/main.js
> +}
pH level is a continuous scale from `0` to `14`. Blood (pH of 7.4) and milk (pH of 6.45) should be classified correctly:

---

![image](https://user-images.githubusercontent.com/16143771/169163550-3da00774-ae16-472a-a0c3-06adcc81e250.png)

2022-05-23 16:29 UTC, Zhiwutian approved these changes
👍🏼

2022-05-23 16:35 UTC, merged